version: '3'
services:
  elasticsearch:
    container_name: es01
    environment:
      - discovery.type=single-node     
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
        #- ./elastic-certificates.p12:/usr/share/elasticsearch/config/elastic-certificates.p12
        #- ./docker-data-volumes/elasticsearch:/usr/share/elasticsearch/data

  kibana:
   container_name: kib01
   depends_on:
     - elasticsearch
   image: docker.elastic.co/kibana/kibana:7.10.1
   ports:
     - 5601:5601
   volumes:
     - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  db:
    image: mariadb:focal
    restart: always
    container_name: mdb1
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "camtec"
    volumes:
      - ./docker-data-volumes/mariadb:/var/lib/mysql


